name: check-branches
on:
  - pull_request

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Lint Bash scripts
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -x
        with:
          scandir: "./scripts"
      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@v1.2.1
        with:
          dockerfile: Dockerfile
