on: push

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: mpsq/emacs-native-comp-wayland-builder:latest

  artifact:
    runs-on: ubuntu-latest
    needs: [image]
    container: mpsq/emacs-native-comp-wayland-builder:latest
    steps:
      - name: Get name
        run: |
          echo "emacs_artifact_name=$(ls /home/pcr)" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ env.emacs_artifact_name }}
          path: /home/pcr/${{ env.emacs_artifact_name }}
