on:
  schedule:
    - cron: "0 4,10,16,22 * * *"

jobs:
  image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: mpsq/emacs-native-comp-wayland-builder:latest

  artifact:
    runs-on: ubuntu-latest
    needs: [image]
    container:
      image: mpsq/emacs-native-comp-wayland-builder:latest
      options: --user root
    steps:
      - name: Prepare artifacts
        run: |
          cd /home/pcr
          mkdir sources
          ver=$(ls emacs* | sed -r 's/.*([0-9]{2}\.[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{6}).*/\1/gi')
          #git clone ssh://aur@aur.archlinux.org/emacs-gcc-wayland-devel-bin.git
          #old_ver=$(cat PKGBUILD | grep "pkgver=" | sed -r 's/pkgver=//')
          #[[ "$old_ver" == "$ver" ]] && exit 1
          echo "pkg_version=$ver" >> $GITHUB_ENV
          tar xf "$(ls emacs*)" -C sources
          rm sources/.BUILDINFO sources/.MTREE sources/.PKGINFO
      - uses: actions/upload-artifact@v2
        with:
          name: emacs-gcc-wayland-devel-${{ env.pkg_version }}
          path: /home/pcr/sources
