name: build-manual
on:
  workflow_dispatch:
    inputs:
      new_commit_n:
        description: "Commit for last release"
        required: true
      old_commit_n:
        description: "Commit # for upstream"
        required: true

env:
  UPSTREAM_API: https://api.github.com/repos/flatwhatson/emacs
  UPSTREAM_BRANCH: pgtk-nativecomp
  UPSTREAM_REPO: https://github.com/flatwhatson/emacs
  UPSTREAM_SRC: https://raw.githubusercontent.com/flatwhatson/emacs/pgtk-nativecomp

jobs:
  check:
    runs-on: ubuntu-20.04
    env:
      OLD_COMMIT_N: ${{ github.event.inputs.old_commit_n }}
      NEW_COMMIT_N: ${{ github.event.inputs.new_commit_n }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Check last version
        run: bash ./ci/check-last-version.bash
      - name: Set env vars
        id: var
        run: . ./ci/set-env-vars.bash
    outputs:
      pkg_version: ${{ steps.var.outputs.pkg_version }}

  artifact:
    runs-on: ubuntu-20.04
    needs: check
    container:
      image: mpsq/emacs-builder:latest
      options: --user root
    env:
      OLD_COMMIT_N: ${{ github.event.inputs.old_commit_n }}
      NEW_COMMIT_N: ${{ github.event.inputs.new_commit_n }}
      PKG_VERSION: ${{ needs.check.outputs.pkg_version }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Patch glibc
        run: bash ./ci/patch-glibc.bash
      - name: Build artifacts
        run: bash ./ci/build-artifacts.bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: emacs-manual-build
          path: /home/pcr/${{ needs.check.outputs.pkg_version }}.tar.gz
          retention-days: 5
