name: build-manual
on:
  workflow_dispatch:
    inputs:
      new_commit_n:
        description: "Commit for last release"
        required: true
      old_commit_n:
        description: "Commit # for upstream"
        required: true

env:
  OLD_COMMIT_N: ${{ github.event.inputs.old_commit_n }}
  NEW_COMMIT_N: ${{ github.event.inputs.new_commit_n }}

jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Check last version
        run: bash ./ci/check-last-version.bash
      - name: Import environment variables
        shell: bash
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < .env
      - name: Set env vars
        id: var
        run: . ./ci/set-env-vars.bash
    outputs:
      pkg_version: ${{ steps.var.outputs.pkg_version }}

  artifact:
    runs-on: ubuntu-20.04
    needs: check
    container:
      image: mpsq/emacs-builder:latest
      options: --user root
    env:
      PKG_VERSION: ${{ needs.check.outputs.pkg_version }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Import environment variables
        shell: bash
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < .env
      - name: Patch glibc
        run: bash ./ci/patch-glibc.bash
      - name: Build artifacts
        run: bash ./ci/build-artifacts.bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: emacs-manual-build
          path: ${{ env.HOME }}/${{ needs.check.outputs.pkg_version }}.tar.gz
          retention-days: 5
